--- 
name: "ValidateSimple"
description: "Simple form validation with good UX"
category: "Forms"
tags: 
  - "validation"
current: "0.2"
author: "3n"
contact: "ian.collins@gmail.com"
website: "http://www.iancollins.me"
demo: "https://www.banksimple.com"
sources:
  - "Source/ValidateSimple.js"